export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as ForgotPassword } from './ForgotPassword'
export { default as AddPost } from './AddPost'
export { default as Profile } from './Profile'
export { default as SinglePost } from './SinglePost'